used-permission-INTERNET
used-permission-READ_PHONE_STATE
used-permission-RECEIVE_SMS
used-permission-WRITE_SMS
used-method-android-content-ContextgetResources
used-permission-ACCESS_FINE_LOCATION
used-permission-VIBRATE
apk-folder-res-raw
used-type-java-util-Random
used-permission-ACCESS_COARSE_LOCATION
used-permission-WAKE_LOCK
used-method-android-view-MotionEventgetAction
used-permission-READ_CONTACTS
used-permission-CAMERA
used-permission-CALL_PHONE
used-permission-ACCESS_GPS
used-permission-RECEIVE_BOOT_COMPLETED
used-permission-ACCESS_WIFI_STATE
used-permission-SEND_SMS
used-method-android-view-MotionEventgetX
used-permission-RESTART_PACKAGES
used-permission-READ_SMS
used-method-java-util-RandomnextInt
used-permission-WRITE_CONTACTS
used-permission-READ_LOGS
......
